### PR TITLE
Aging WIP

### PR DESCRIPTION
**Pull request by cifu89**
Adding some tips to be followed during the Daily regarding Aging WIP metric.

### CODE REVIEW

**Comment by GarciaInes** [comment]
Hiya please review the current folder structure and add into the existing each Indicators files rather than a new entry elsewhere. So we keep it consistent!

**Review by GarciaInes — CHANGES_REQUESTED** [review]
Hiya please review the current folder structure and add into the existing each Indicators files rather than a new entry elsewhere. So we keep it consistent!

**Comment by cifu89** [comment]
I've just made the changes

**Review by GarciaInes — APPROVED** [review]
Edited to fit with existing structure, avoid tools promotion and removal potential baggage

**Pull request merged**
